Comp-u-Lock-Web/config/routes.rb
CompULockWeb::Application.routes.draw do
  root :to => "home#index"
  
  resource :home, only: [:index]
  resource :user, only: [:index, :list]
  resources :computer
  resources :account
  
  namespace :api, defaults:{format:'json'} do
    namespace :v1  do
      resources :tokens, only: [:create, :destroy] # done
      resources :computers, only: [:index, :show, :create, :update, :destroy]
      resources :users, only: [:index, :update] # done
      resources :accounts, only: [:index, :create, :update, :show, :destroy] # Update
      resources :histories, only: [:create, :show, :index]
      resources :processes, only: [:create, :show, :index]
      resources :programs, only: [:create, :show, :index]
    end
  end

  devise_for :users
  devise_scope :user do 
    match '/users/sign_in' => 'devise/session#create', :as => :new_user_session
    match '/users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
    match '/users/edit' => 'devise/registrations#edit', :as => :user_edit
  end

  match 'users/profile', as: :user_profile
  match ':controller(/:action(/:id))(.:format)'
end

Comp-u-Lock-Web/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

Comp-u-Lock-Web/app/views/layouts/_navigation.html.erb
<%= link_to "Comp-u-Lock", root_path, class: 'brand'%>
<ul class="nav">
	<% unless signed_in? %>
	<li><%= link_to('Login', new_user_session_path, :style =>"color: green")  %></li>
	<li><%= link_to('Register', new_user_registration_path, :style =>"color: green")  %></li>
	<%else%>
	<li><%= link_to("Profile", user_profile_path) %></li>
	<li><%= link_to('Computers', computer_index_path) %></li>
	<li><%= link_to('Computer Accounts', account_index_path) %></li>
	<li><%= link_to('Logout', destroy_user_session_path, :method=>'get', :style => "color: #A80000") %></li>
	<% if current_user.admin? %>
	<li><%= link_to("User List", user_list_path) %></li>
	<%end%>
	<%end%>
</ul>

Comp-u-Lock-Web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CompULockWeb</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-fixed-top">
		<nav class="navbar-inner">
			<div class="container">
				<%= render 'layouts/navigation' %>
			</div>
		</nav>
	</header>
	<div id="main" role="main">
		<%= render 'layouts/messages' %>
		<div class="container">
        	<div class="content">
           		<div class="row">
            		<div class="span12">
						<%= yield %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<footer>
		<div class="container">
	        <hr>
	        <div class="row">
	          <div class="span3">
	            <p class="muted credit">Brought to you by</p>Comp-u-Lock
	          </div>
	        </div>
	      </div>
	</footer>
</body>
</html>